// CREATE
export const POST_WRITE_REQUEST = 'POST_WRITE_REQUEST';
export const POST_WRITE_SUCCESS = 'POST_WRITE_SUCCESS';
export const POST_WRITE_FAILURE = 'POST_WRITE_FAILURE';

// READ // DETAIL
export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAILURE = 'POST_DETAIL_FAILURE';

// READ // TOP RATED POSTS
export const TOP_RATED_POSTS_REQUEST = 'TOP_RATED_POSTS_REQUEST';
export const TOP_RATED_POSTS_SUCCESS = 'TOP_RATED_POSTS_SUCCESS';
export const TOP_RATED_POSTS_FAILURE = 'TOP_RATED_POSTS_FAILURE';

// READ // LIST
export const POST_LOADING_REQUEST = 'POST_LOADING_REQUEST';
export const POST_LOADING_SUCCESS = 'POST_LOADING_SUCCESS';
export const POST_LOADING_FAILURE = 'POST_LOADING_FAILURE';

// READ // ALL LIST
export const ALL_POST_LOADING_REQUEST = 'ALL_POST_LOADING_REQUEST';
export const ALL_POST_LOADING_SUCCESS = 'ALL_POST_LOADING_SUCCESS';
export const ALL_POST_LOADING_FAILURE = 'ALL_POST_LOADING_FAILURE';

// UPDATE // PAGE
export const POST_EDITPAGE_REQUEST = 'POST_EDITPAGE_REQUEST';
export const POST_EDITPAGE_SUCCESS = 'POST_EDITPAGE_SUCCESS';
export const POST_EDITPAGE_FAILURE = 'POST_EDITPAGE_FAILURE';

// UPDATE // ACTION
export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE';

// DELETE
export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';

// LOAD USER POST
export const LOADING_USER_POST_REQUEST = 'LOADING_USER_POST_REQUEST';
export const LOADING_USER_POST_SUCCESS = 'LOADING_USER_POST_SUCCESS';
export const LOADING_USER_POST_FAILURE = 'LOADING_USER_POST_FAILURE';

// VIEW LOAD
export const POST_LOADVIEW_REQUEST = 'POST_LOADVIEW_REQUEST';
export const POST_LOADVIEW_SUCCESS = 'POST_LOADVIEW_SUCCESS';
export const POST_LOADVIEW_FAILURE = 'POST_LOADVIEW_FAILURE';

// VIEW UP
export const POST_UPVIEW_REQUEST = 'POST_UPVIEW_REQUEST';
export const POST_UPVIEW_SUCCESS = 'POST_UPVIEW_SUCCESS';
export const POST_UPVIEW_FAILURE = 'POST_UPVIEW_FAILURE';

// CATEGORY FIND
export const CATEGORY_FIND_REQUEST = 'CATEGORY_FIND_REQUEST';
export const CATEGORY_FIND_SUCCESS = 'CATEGORY_FIND_SUCCESS';
export const CATEGORY_FIND_FAILURE = 'CATEGORY_FIND_FAILURE';

// SEARCH
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
